server:
  port: 7901

spring:
  application:
    name: config-discovery-eureka-client-consumer-ribbon-without-eureka            
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://lin:lin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${server.port}
    
    
ribbon:
  eureka:
   enabled: false
   
config-discovery-eureka-client-producer:
  ribbon:
    listOfServers: localhost:8764,localhost:8765